// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Backend.DAL.Models
{
    public partial class Town
    {
        public Town()
        {
            School = new HashSet<School>();
        }

        public int Id { get; set; }
        public int Postcode { get; set; }
        public string Name { get; set; }

        public virtual ICollection<School> School { get; set; }
    }
}