// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Backend.DAL.Models
{
    public partial class Workshop
    {
        public Workshop()
        {
            WorkshopParticipant = new HashSet<WorkshopParticipant>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime Time { get; set; }
        public int SchoolId { get; set; }
        public int Capacity { get; set; }

        public virtual School School { get; set; }
        public virtual ICollection<WorkshopParticipant> WorkshopParticipant { get; set; }
    }
}