// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Backend.DAL.Models
{
    public partial class WorkshopParticipant
    {
        public int Id { get; set; }
        public int ParticipantId { get; set; }
        public int WorkshopId { get; set; }
        public DateTime ApplicationTime { get; set; }

        public virtual Student Participant { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}